Repository IntelLabs/encrypted-computing-sdk, pull requests merged in 2025-06, with the labels that each got.

#77 [hec-assembler]: Refactoring no_hbm option for Configurable ISA_spec
  assembler_tools/hec-assembler-tools/assembler/instructions/cinst/csyncm.py
  assembler_tools/hec-assembler-tools/assembler/isa_spec/cinst/__init__.py
  assembler_tools/hec-assembler-tools/assembler/isa_spec/minst/__init__.py
  assembler_tools/hec-assembler-tools/assembler/isa_spec/xinst/__init__.py
  assembler_tools/hec-assembler-tools/he_link.py
  assembler_tools/hec-assembler-tools/linker/steps/program_linker.py
Labels: bug, python

#80 [hec-assembler]: Enable Configurable Memory Specification
  assembler_tools/hec-assembler-tools/README.md
  assembler_tools/hec-assembler-tools/assembler/common/constants.py
  assembler_tools/hec-assembler-tools/assembler/common/run_config.py
  assembler_tools/hec-assembler-tools/assembler/memory_model/__init__.py
  assembler_tools/hec-assembler-tools/assembler/memory_model/register_file.py
  assembler_tools/hec-assembler-tools/assembler/spec_config/isa_spec.py
  assembler_tools/hec-assembler-tools/assembler/spec_config/mem_spec.py
  assembler_tools/hec-assembler-tools/assembler/stages/asm_scheduler.py
  assembler_tools/hec-assembler-tools/config/mem_spec.json
  assembler_tools/hec-assembler-tools/he_as.py
  assembler_tools/hec-assembler-tools/he_link.py
  assembler_tools/hec-assembler-tools/he_prep.py
Labels: documentation, enhancement, python

#78 [hec-assembler]: Fix suggested bank error
  assembler_tools/hec-assembler-tools/assembler/stages/asm_scheduler.py
Labels: bug, python

#81 Experimental - Initial commit for Kerngraph
  p-isa_tools/kerngen/const/options.py
  p-isa_tools/kerngen/high_parser/types.py
  p-isa_tools/kerngen/kernel_optimization/__init__.py
  p-isa_tools/kerngen/kernel_optimization/loops.py
  p-isa_tools/kerngen/kernel_parser/__init__.py
  p-isa_tools/kerngen/kernel_parser/parser.py
  p-isa_tools/kerngen/kerngraph.py
  p-isa_tools/kerngen/tests/test_kerngraph_command.py
  p-isa_tools/kerngen/tests/test_kerngraph_parser.py
Labels: enhancement, Experimental
